name: GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install documentation requirements
        run: |
          pip install -r docs/requirements.txt

      - name: Make docs builds
        run: |
          make -C docs html O="-t release"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
